# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Parstagram' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

 pod 'Parse'
 pod 'Alamofire'
 pod 'AlamofireImage'

  # Pods for Parstagram

  target 'ParstagramTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ParstagramUITests' do
    # Pods for testing
  end

end
